#include <stdio.h>

// This runtime is used to run the assembly code generated by our compiler. This
// program prints out the value returned by the user program.

/* define all scheme constants */

// Scheme fixnums.
//
// Fixnums always have #b00 in the two least-significant bits. The
// most-significant 30-bits represent the actual value of the fixnum. This means
// our fixnums have a range of −229 ≤ n ≤ 229 − 1 or −536870912 ≤ n ≤ 536870911.
//
// The mask, tag and shift are used together to check if a word is a fixnum, and
// to shift appropriately to get the true value.
#define fx_mask      0x03
#define fx_tag       0x00
#define fx_shift     2

// All other immediate constants (boolean, char, empty list [null]) have #b1111
// as its tag.

#define nil          0x3F // 0b00111111
#define bool_f       0x2F // 0b00101111
#define bool_t       0x6F // 0b01101111

// Chars uses two bytes. Lower byte is 0b00001111.
// Upper byte is the ASCII value.
#define char_mask    0xFF // 0b11111111
#define char_tag     0x0F // 0b00001111
#define char_shift   8

/* all scheme values are of type ptrs */
typedef unsigned int ptr;

int scheme_entry();

static void print_ptr(ptr x) {
  if ((x & fx_mask) == fx_tag) {
    // A fixnum.
    printf("%d", ((int)x) >> fx_shift);
  } else if (x == bool_f) {
    printf("#f");
  } else if (x == bool_t) {
    printf("#t");
  } else if (x == nil) {
    printf("()");
  } else if ((x & char_mask) == char_tag) {
    switch ((int)x >> char_shift) {
      case 9:
        printf("#\\tab");
        break;
      case 10:
        printf("#\\newline");
        break;
      case 13:
        printf("#\\return");
        break;
      case 32:
        printf("#\\space");
        break;
      default:
        printf("#\\%c", (int)x >> char_shift);
        break;
    }
  } else {
    printf("#<unknown 0x%08x>", x);
  }
  printf("\n");
}

int main(int argc, char** argv) {
  print_ptr(scheme_entry());
  return 0;
}
