
(add-tests-with-string-output "if"
  [(if #t 12 13) => "12\n"]
  [(if #f 12 13) => "13\n"]
  [(if 0 12 13)  => "12\n"]
  [(if () 43 ()) => "43\n"]
  [(if #t (if 12 13 4) 17) => "13\n"]
  [(if #f 12 (if #f 13 4)) => "4\n"]
  [(if #\X (if 1 2 3) (if 4 5 6)) => "2\n"]
  [(if (not (boolean? #t)) 15 (boolean? #f)) => "#t\n"]
  [(if (if (char? #\a) (boolean? #\b) (fixnum? #\c)) 119 -23) => "-23\n"]
  [(if (if (if (not 1) (not 2) (not 3)) 4 5) 6 7) => "6\n"] 
  [(if (not (if (if (not 1) (not 2) (not 3)) 4 5)) 6 7) => "7\n"] 
  [(not (if (not (if (if (not 1) (not 2) (not 3)) 4 5)) 6 7)) => "#f\n"] 
  [(if (char? 12) 13 14) => "14\n"]
  [(if (char? #\a) 13 14) => "13\n"]
  [(fxadd1 (if (fxsub1 1) (fxsub1 13) 14)) => "13\n"]
)

(add-tests-with-string-output "and"
  [(and) => "#t\n"]
  [(and #t) => "#t\n"]
  [(and #f) => "#f\n"]
  [(and 123) => "123\n"]
  [(and (not (not #t))) => "#t\n"]
  [(and #t #f) => "#f\n"]
  [(and #f #t) => "#f\n"]
  [(and #t (fxzero? 1)) => "#f\n"]
  [(and #t (fxzero? 0) #t (null? ())) => "#t\n"]
  [(and #t (fxzero? 0) #t (null? 3)) => "#f\n"]
  [(and (and (and 3 #t 5))) => "5\n"]
  [(if (and) 3 4) => "3\n"]
  [(if (and #f) 3 4) => "4\n"]
  [(if (and 123) 3 4) => "3\n"]
  [(if (and (not (not #t))) (and) 4) => "#t\n"]
  [(if (and #t #f) 3 4) => "4\n"]
  [(if (and #f #t) 3 4) => "4\n"]
  [(if (and #t (fxzero? 0) #t (null? ())) 3 4) => "3\n"]
  [(if (and #t (fxzero? 0) #t (null? 3)) 3 4) => "4\n"]
  [(if (and #t (fxzero? 0) #t (null? 3)) 3 (and #t (null? ()))) => "#t\n"]
)

(add-tests-with-string-output "or"
  [(or) => "#t\n"]
  [(or #t) => "#t\n"]
  [(or #f) => "#f\n"]
  [(or 123) => "123\n"]
  [(or (not (not #t))) => "#t\n"]
  [(or #t #f) => "#t\n"]
  [(or #f #t) => "#t\n"]
  [(or #f #f) => "#f\n"]
  [(or (fxzero? 1) (fxzero? 2)) => "#f\n"]
  [(or (fxzero? 0) (null? ()) #f) => "#t\n"]
  [(or (fxzero? 1) (null? 3)) => "#f\n"]
  [(or 123 (fxzero? 1) (null? 3)) => "123\n"]
  [(or (or (or 3 #t 5))) => "3\n"]
  [(if (or) 3 4) => "3\n"]
  [(if (or #f) 3 4) => "4\n"]
  [(if (or 123) 3 4) => "3\n"]
  [(if (or (not (not #t))) (or) 4) => "#t\n"]
  [(if (or #t #f) 3 4) => "3\n"]
  [(if (or #t (fxzero? 0) #t (null? ())) 3 4) => "3\n"]
  [(if (or #f (fxzero? 1) #f (null? 3)) 3 4) => "4\n"]
  [(if (or #f (fxzero? 1) #f (null? 3)) 3 (or #f (null? ()))) => "#t\n"]
  [(or (and 1 2 3) (and 4 5 6)) => "3\n"]
  [(or (and 1 2 (or 3 #f)) (and 4 5 6)) => "3\n"]
  [(and (and 1 2 (or 3 #f)) (and 4 5 6)) => "6\n"]
  [(if (and (and 1 2 (or 3 #f)) (and 4 5 6)) 1 2) => "1\n"]
)
